#网站基本信息
site_name: 白泽史料库-冷战
site_description: 介绍冷战（1945-1991）发生的历史事件，并对部分重大历史事件进行评析
site_author: FutureStand

#目录，缩进表示子目录关系
nav:
  - intro: index.md
  - 战后格局逐步形成:
    - 百分比协定: './after_ww2/percentages.md'
  - 冷战格局初现:
    - 地缘政治:
      - 苏土海峡危机: './cold_war_come/turkey.md'
      - 希腊内战: './cold_war_come/greece_war.md'

theme: 
  name: material