#网站基本信息
site_name: 白泽史料库-冷战
site_description: 介绍冷战（1945-1991）发生的历史事件，并对部分重大历史事件进行评析
site_author: FutureStand

repo_name: FutureStand/BaiZe-ColdWar
repo_url: https://github.com/FutureStand/BaiZe-ColdWar

#目录，缩进表示子目录关系
nav:
  - 序：对立的世界: index.md
  - 向冷战奔去:
    - 战后格局:
      - 百分比协定: './after_ww2/percentages.md'
    - 冷战格局初现:
      - 苏土海峡危机: './cold_war_come/turkey.md'
      - 希腊内战: './cold_war_come/greece_war.md'

theme: 
  name: material
  #主题设置
  language: 'zh'
  palette:
    primary: 'pink'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  
#Markdown 语法扩展
markdown_extensions:
  - admonition #MkDocs 警告框
  - footnotes #脚注
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - pymdownx.keys
  - pymdownx.emoji: #更多emoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.smartsymbols