#网站基本信息
site_name: 白泽史料库-冷战
site_description: 介绍冷战（1945-1991）发生的历史事件，并对部分重大历史事件进行评析
site_author: FutureStand

repo_name: FutureStand/BaiZe-ColdWar
repo_url: https://github.com/FutureStand/BaiZe-ColdWar

#目录，缩进表示子目录关系
nav:
  - cold-war.md
  - 向冷战奔去: 
    - 'chap1/index.md'
    - 战后格局:
      - 百分比协定: 'chap1/percentages.md'
      - 雅尔塔会议: 'chap1/yalta.md'
      - 波茨坦会议: 'chap1/potsdam.md'
    - 冷战格局初现:
      - 苏土海峡危机: 'chap1/turkey.md'
      - 希腊内战: 'chap1/greece_war.md'
      - 苏南交恶: 'chap1/yugoslavia.md'
  - 对立的阵营:
    - 'chap2/index.md'

theme: 
  name: material
  #主题设置
  language: 'zh'
  palette:
    primary: 'pink'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  features:
    - content.code.annotate
    #返回顶部
    - navigation.top
    - navigation.indexes
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  
#Markdown 语法扩展
markdown_extensions:
  - admonition #MkDocs 警告框
  - attr_list #开启额外css支持，包括按钮
  - footnotes #脚注
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - pymdownx.keys
  - pymdownx.emoji: #更多emoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences #开启注释功能
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - md_in_html